import type { Metadata } from 'next'
import { Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'

import { Providers } from '@/components/providers'

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Syntesa | Pinjam Lab.'
  // description: "Generated by create next app",
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${plusJakartaSans.className} bg-white text-primary antialiased dark:bg-gray-900`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
